/**
 * Badges de Atividade Social - 12 badges
 */

import { BadgeDefinition } from './types';

export const socialBadges: BadgeDefinition[] = [
  {
    badgeId: 'msg_100',
    name: 'Conversador',
    description: 'Enviou 100 mensagens',
    icon: '💬',
    category: 'achievement',
    requirement: { type: 'messages', value: 100 },
    rarity: 'common',
  },
  {
    badgeId: 'msg_1000',
    name: 'Tagarela',
    description: 'Enviou 1.000 mensagens',
    icon: '🗣️',
    category: 'achievement',
    requirement: { type: 'messages', value: 1000 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'msg_5000',
    name: 'Comunicador',
    description: 'Enviou 5.000 mensagens',
    icon: '📢',
    category: 'achievement',
    requirement: { type: 'messages', value: 5000 },
    rarity: 'rare',
  },
  {
    badgeId: 'msg_10000',
    name: 'Orador',
    description: 'Enviou 10.000 mensagens',
    icon: '🎤',
    category: 'achievement',
    requirement: { type: 'messages', value: 10000 },
    rarity: 'epic',
  },
  {
    badgeId: 'voice_10h',
    name: 'Na Call',
    description: '10 horas em canais de voz',
    icon: '🎧',
    category: 'achievement',
    requirement: { type: 'voice_hours', value: 10 },
    rarity: 'common',
  },
  {
    badgeId: 'voice_50h',
    name: 'Vocalista',
    description: '50 horas em canais de voz',
    icon: '🎵',
    category: 'achievement',
    requirement: { type: 'voice_hours', value: 50 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'voice_200h',
    name: 'DJ',
    description: '200 horas em canais de voz',
    icon: '🎶',
    category: 'achievement',
    requirement: { type: 'voice_hours', value: 200 },
    rarity: 'rare',
  },
  {
    badgeId: 'voice_500h',
    name: 'Streamer',
    description: '500 horas em canais de voz',
    icon: '📺',
    category: 'achievement',
    requirement: { type: 'voice_hours', value: 500 },
    rarity: 'epic',
  },
  {
    badgeId: 'react_500',
    name: 'Reativo',
    description: 'Deu 500 reacoes',
    icon: '👍',
    category: 'achievement',
    requirement: { type: 'reactions_given', value: 500 },
    rarity: 'common',
  },
  {
    badgeId: 'react_popular',
    name: 'Popular',
    description: 'Recebeu 500 reacoes',
    icon: '⭐',
    category: 'achievement',
    requirement: { type: 'reactions_received', value: 500 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'streak_30',
    name: 'Consistente',
    description: '30 dias consecutivos de daily',
    icon: '🔥',
    category: 'achievement',
    requirement: { type: 'streak', value: 30 },
    rarity: 'rare',
  },
  {
    badgeId: 'streak_100',
    name: 'Inabalavel',
    description: '100 dias consecutivos de daily',
    icon: '💯',
    category: 'achievement',
    requirement: { type: 'streak', value: 100 },
    rarity: 'legendary',
  },
];
