/**
 * Badges de Hardware Geral - 15 badges
 */

import { BadgeDefinition } from './types';

export const hardwareBadges: BadgeDefinition[] = [
  {
    badgeId: 'hw_first_build',
    name: 'Primeiro Build',
    description: 'Postou seu primeiro PC montado',
    icon: '🔧',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'hw_cpu_intel',
    name: 'Team Blue',
    description: 'Compartilhou setup com CPU Intel',
    icon: '🔵',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'hw_cpu_amd',
    name: 'Team Red',
    description: 'Compartilhou setup com CPU AMD',
    icon: '🔴',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'hw_gpu_nvidia',
    name: 'Team Green',
    description: 'Setup com GPU Nvidia',
    icon: '💚',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'hw_gpu_amd',
    name: 'Radeon Gang',
    description: 'Setup com GPU AMD Radeon',
    icon: '❤️',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'hw_dual_gpu',
    name: 'SLI/CrossFire',
    description: 'Setup com dual GPU',
    icon: '👯',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'hw_32gb_ram',
    name: 'RAM Lover',
    description: '32GB+ de RAM no setup',
    icon: '🧠',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'hw_64gb_ram',
    name: 'RAM Hoarder',
    description: '64GB+ de RAM no setup',
    icon: '🤯',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'hw_nvme',
    name: 'Velocidade Maxima',
    description: 'SSD NVMe no setup',
    icon: '⚡',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'hw_raid',
    name: 'RAID Master',
    description: 'Configuracao RAID ativa',
    icon: '💾',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'hw_10gbe',
    name: 'Network Pro',
    description: 'Rede 10GbE em casa',
    icon: '🌐',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'hw_server',
    name: 'Homelab',
    description: 'Possui servidor em casa',
    icon: '🖥️',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'hw_workstation',
    name: 'Workstation',
    description: 'PC de trabalho profissional',
    icon: '💼',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'hw_vintage',
    name: 'Colecionador Vintage',
    description: 'Possui hardware retro/vintage',
    icon: '📼',
    category: 'hardware',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'hw_reviewer',
    name: 'Tech Reviewer',
    description: 'Fez 5+ reviews de hardware',
    icon: '📝',
    category: 'hardware',
    requirement: { type: 'manual', value: 5 },
    rarity: 'epic',
  },
];
