/**
 * Badges de Overclocking - 20 badges
 */

import { BadgeDefinition } from './types';

export const overclockingBadges: BadgeDefinition[] = [
  {
    badgeId: 'oc_first',
    name: 'Primeiro OC',
    description: 'Postou seu primeiro overclock',
    icon: '⚡',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'oc_cpu_5ghz',
    name: '5GHz Club',
    description: 'CPU rodando a 5GHz+',
    icon: '🏃',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'oc_cpu_6ghz',
    name: '6GHz Club',
    description: 'CPU rodando a 6GHz+',
    icon: '🚀',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'oc_cpu_7ghz',
    name: '7GHz Club',
    description: 'CPU rodando a 7GHz+ (resfriamento extremo)',
    icon: '💨',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'oc_cpu_8ghz',
    name: '8GHz Club',
    description: 'CPU rodando a 8GHz+ (LN2)',
    icon: '🌡️',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'oc_gpu_oc',
    name: 'GPU Tuner',
    description: 'GPU com overclock aplicado',
    icon: '🎮',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'oc_gpu_extreme',
    name: 'GPU Extreme',
    description: 'GPU OC extremo (+300MHz core)',
    icon: '🔥',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'oc_ram_xmp',
    name: 'XMP Enabled',
    description: 'RAM com XMP/EXPO ativado',
    icon: '💾',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'oc_ram_manual',
    name: 'RAM Tuner',
    description: 'RAM com timings tunados manualmente',
    icon: '⚙️',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'oc_ram_extreme',
    name: 'RAM Extreme',
    description: 'RAM rodando a 6000MHz+',
    icon: '🧊',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'oc_bencher',
    name: 'Bencher',
    description: 'Postou benchmark validado',
    icon: '📊',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'oc_top100',
    name: 'Top 100',
    description: 'Top 100 em benchmark no HWBot',
    icon: '🏅',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'oc_top10',
    name: 'Top 10',
    description: 'Top 10 em benchmark no HWBot',
    icon: '🥇',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'oc_world_record',
    name: 'World Record',
    description: 'Detentor de recorde mundial',
    icon: '🌍',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'oc_ln2_user',
    name: 'LN2 User',
    description: 'Usa nitrogenio liquido para OC',
    icon: '🧊',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'oc_dice_user',
    name: 'DICE User',
    description: 'Usa gelo seco para OC',
    icon: '🎲',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'oc_chiller',
    name: 'Chiller User',
    description: 'Usa chiller para resfriamento',
    icon: '❄️',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'oc_daily_driver',
    name: 'Daily OC',
    description: 'Overclock 24/7 estavel',
    icon: '🚗',
    category: 'overclocking',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'oc_validator',
    name: 'Validador',
    description: '10+ validacoes no HWBot',
    icon: '✅',
    category: 'overclocking',
    requirement: { type: 'manual', value: 10 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'oc_mentor',
    name: 'OC Mentor',
    description: 'Ajudou 10+ pessoas com overclock',
    icon: '🎓',
    category: 'overclocking',
    requirement: { type: 'manual', value: 10 },
    rarity: 'epic',
  },
];
