/**
 * Badges de Setup Wars - 12 badges
 */

import { BadgeDefinition } from './types';

export const setupwarsBadges: BadgeDefinition[] = [
  {
    badgeId: 'setup_first',
    name: 'Primeiro Setup',
    description: 'Postou seu primeiro setup',
    icon: '📸',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'setup_clean',
    name: 'Clean Setup',
    description: 'Setup organizado aprovado pela comunidade',
    icon: '✨',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'setup_rgb',
    name: 'RGB Master',
    description: 'Setup com RGB sincronizado impecavel',
    icon: '🌈',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'setup_minimal',
    name: 'Minimalista',
    description: 'Setup minimalista elegante',
    icon: '⬜',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'setup_battlestation',
    name: 'Battlestation',
    description: 'Setup gamer completo',
    icon: '🎮',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'setup_ultrawide',
    name: 'Ultrawide Gang',
    description: 'Setup com monitor ultrawide',
    icon: '🖥️',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'setup_multimon',
    name: 'Multi-Monitor',
    description: 'Setup com 3+ monitores',
    icon: '🖥️',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'setup_cable_mgmt',
    name: 'Cable Master',
    description: 'Cable management perfeito',
    icon: '🔌',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'setup_winner',
    name: 'Setup Winner',
    description: 'Venceu competicao de setup',
    icon: '🏆',
    category: 'setup',
    requirement: { type: 'competition', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'setup_featured',
    name: 'Featured Setup',
    description: 'Setup destacado pela staff',
    icon: '⭐',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'setup_influencer',
    name: 'Setup Influencer',
    description: 'Setup com 50+ likes na comunidade',
    icon: '📱',
    category: 'setup',
    requirement: { type: 'manual', value: 50 },
    rarity: 'rare',
  },
  {
    badgeId: 'setup_legendary',
    name: 'Setup Lendario',
    description: 'Setup iconico reconhecido pela comunidade',
    icon: '👑',
    category: 'setup',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
];
