/**
 * Badges de Perifericos - 14 badges
 */

import { BadgeDefinition } from './types';

export const peripheralsBadges: BadgeDefinition[] = [
  {
    badgeId: 'periph_mech_kb',
    name: 'Mech Enthusiast',
    description: 'Possui teclado mecanico',
    icon: '⌨️',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'periph_custom_kb',
    name: 'Custom KB',
    description: 'Possui teclado mecanico custom',
    icon: '🎹',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'periph_kb_collector',
    name: 'KB Collector',
    description: 'Coleciona 3+ teclados mecanicos',
    icon: '🗃️',
    category: 'peripherals',
    requirement: { type: 'manual', value: 3 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'periph_switches',
    name: 'Switch Guru',
    description: 'Conhecedor de switches mecanicos',
    icon: '🔘',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'periph_mouse_gaming',
    name: 'Gaming Mouse',
    description: 'Possui mouse gamer',
    icon: '🖱️',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'periph_mouse_collector',
    name: 'Mouse Collector',
    description: 'Coleciona 3+ mouses',
    icon: '🐭',
    category: 'peripherals',
    requirement: { type: 'manual', value: 3 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'periph_mousepad_xl',
    name: 'Desk Mat',
    description: 'Usa mousepad XL ou deskmat',
    icon: '🟫',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'periph_headset',
    name: 'Audiofilo',
    description: 'Possui headset ou fone de qualidade',
    icon: '🎧',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'periph_dac_amp',
    name: 'DAC/AMP User',
    description: 'Usa DAC ou amplificador de audio',
    icon: '🔊',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'periph_speakers',
    name: 'Speaker Setup',
    description: 'Sistema de som dedicado no setup',
    icon: '🔈',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'periph_mic',
    name: 'Podcaster',
    description: 'Microfone dedicado no setup',
    icon: '🎙️',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'periph_stream_deck',
    name: 'Stream Deck',
    description: 'Usa Stream Deck ou similar',
    icon: '🎛️',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'periph_controller',
    name: 'Controller Pro',
    description: 'Controle premium para jogos',
    icon: '🎮',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'periph_sim',
    name: 'Sim Racer',
    description: 'Setup completo de simulacao',
    icon: '🏎️',
    category: 'peripherals',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
];
