/**
 * Badges de Impressao 3D - 15 badges
 */

import { BadgeDefinition } from './types';

export const printBadges: BadgeDefinition[] = [
  {
    badgeId: '3d_first_print',
    name: 'Primeira Impressao',
    description: 'Postou sua primeira impressao 3D',
    icon: '🖨️',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: '3d_pla_master',
    name: 'PLA Master',
    description: 'Domina impressao em PLA',
    icon: '🌽',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: '3d_petg_user',
    name: 'PETG User',
    description: 'Imprime em PETG',
    icon: '🧪',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: '3d_abs_user',
    name: 'ABS Warrior',
    description: 'Imprime em ABS com sucesso',
    icon: '💪',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: '3d_tpu_flex',
    name: 'Flex Master',
    description: 'Imprime em TPU/filamento flexivel',
    icon: '🤸',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: '3d_resin',
    name: 'Resin Printer',
    description: 'Possui impressora de resina',
    icon: '💎',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: '3d_multicolor',
    name: 'Multicolor',
    description: 'Fez impressao multicolorida',
    icon: '🎨',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: '3d_100h',
    name: '100 Horas',
    description: '100 horas de impressao acumuladas',
    icon: '⏱️',
    category: '3dprint',
    requirement: { type: 'manual', value: 100 },
    rarity: 'uncommon',
  },
  {
    badgeId: '3d_500h',
    name: '500 Horas',
    description: '500 horas de impressao acumuladas',
    icon: '⏳',
    category: '3dprint',
    requirement: { type: 'manual', value: 500 },
    rarity: 'rare',
  },
  {
    badgeId: '3d_1000h',
    name: '1000 Horas',
    description: '1000 horas de impressao acumuladas',
    icon: '🕐',
    category: '3dprint',
    requirement: { type: 'manual', value: 1000 },
    rarity: 'epic',
  },
  {
    badgeId: '3d_designer',
    name: '3D Designer',
    description: 'Cria seus proprios modelos 3D',
    icon: '✏️',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: '3d_functional',
    name: 'Functional Prints',
    description: 'Fez prints funcionais para PC/setup',
    icon: '🔧',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: '3d_failed',
    name: 'Fail Expert',
    description: 'Compartilhou fails epicos de impressao',
    icon: '💀',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: '3d_helper',
    name: 'Print Helper',
    description: 'Ajudou outros com problemas de impressao',
    icon: '🤝',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: '3d_commissioned',
    name: 'Commissioned',
    description: 'Faz impressoes por encomenda',
    icon: '💰',
    category: '3dprint',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
];
