/**
 * Badges de Modding - 15 badges
 */

import { BadgeDefinition } from './types';

export const moddingBadges: BadgeDefinition[] = [
  {
    badgeId: 'mod_first',
    name: 'Primeiro Mod',
    description: 'Postou sua primeira modificacao',
    icon: '🔨',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'mod_case_mod',
    name: 'Case Modder',
    description: 'Fez modificacao em gabinete',
    icon: '🗄️',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'mod_paint',
    name: 'Custom Paint',
    description: 'Fez pintura customizada em hardware',
    icon: '🎨',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'mod_vinyl',
    name: 'Vinyl Wrapper',
    description: 'Aplicou vinil em componentes',
    icon: '📦',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'mod_cables',
    name: 'Custom Cables',
    description: 'Possui cabos sleeved customizados',
    icon: '🔌',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'mod_waterblock',
    name: 'Waterblock Mod',
    description: 'Modificou ou customizou waterblock',
    icon: '💧',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'mod_gpu_mod',
    name: 'GPU Modder',
    description: 'Fez modificacao fisica em GPU',
    icon: '🎮',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'mod_delid',
    name: 'Delidder',
    description: 'Fez delid em processador',
    icon: '🔪',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'mod_direct_die',
    name: 'Direct Die',
    description: 'Usa resfriamento direct die',
    icon: '💀',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'mod_bios',
    name: 'BIOS Modder',
    description: 'Modificou BIOS de componente',
    icon: '💾',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'mod_volt_mod',
    name: 'Volt Modder',
    description: 'Fez modificacao de voltagem em hardware',
    icon: '⚡',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'mod_retro',
    name: 'Retro Modder',
    description: 'Modificou hardware retro/vintage',
    icon: '📼',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'mod_full_custom',
    name: 'Full Custom',
    description: 'Build 100% customizado',
    icon: '👑',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'mod_scratch_build',
    name: 'Scratch Build',
    description: 'Construiu gabinete ou componente do zero',
    icon: '🏗️',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'mod_featured',
    name: 'Featured Mod',
    description: 'Mod destacado pela staff',
    icon: '⭐',
    category: 'modding',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
];
