/**
 * Badges de Campeonatos - 15 badges
 */

import { BadgeDefinition } from './types';

export const championshipBadges: BadgeDefinition[] = [
  {
    badgeId: 'comp_participant',
    name: 'Competidor',
    description: 'Participou de um campeonato',
    icon: '🎯',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'comp_5_events',
    name: 'Regular',
    description: 'Participou de 5 campeonatos',
    icon: '🎪',
    category: 'championship',
    requirement: { type: 'competition', value: 5 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'comp_10_events',
    name: 'Frequente',
    description: 'Participou de 10 campeonatos',
    icon: '🏟️',
    category: 'championship',
    requirement: { type: 'competition', value: 10 },
    rarity: 'rare',
  },
  {
    badgeId: 'comp_25_events',
    name: 'Veterano Comp',
    description: 'Participou de 25 campeonatos',
    icon: '🎖️',
    category: 'championship',
    requirement: { type: 'competition', value: 25 },
    rarity: 'epic',
  },
  {
    badgeId: 'comp_top10',
    name: 'Top 10',
    description: 'Top 10 em campeonato',
    icon: '🔟',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'comp_top3',
    name: 'Podio',
    description: 'Top 3 em campeonato',
    icon: '🏆',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'comp_winner',
    name: 'Campeao',
    description: 'Venceu um campeonato',
    icon: '🥇',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'comp_multi_winner',
    name: 'Multi-Campeao',
    description: 'Venceu 3+ campeonatos',
    icon: '👑',
    category: 'championship',
    requirement: { type: 'competition', value: 3 },
    rarity: 'legendary',
  },
  {
    badgeId: 'comp_oc_champ',
    name: 'OC Champion',
    description: 'Campeao de campeonato de overclock',
    icon: '⚡',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'comp_setup_champ',
    name: 'Setup Champion',
    description: 'Campeao de Setup Wars',
    icon: '🖥️',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'comp_mod_champ',
    name: 'Mod Champion',
    description: 'Campeao de campeonato de modding',
    icon: '🔨',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'comp_3d_champ',
    name: '3D Champion',
    description: 'Campeao de campeonato de impressao 3D',
    icon: '🖨️',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'comp_season_winner',
    name: 'Season Winner',
    description: 'Venceu uma temporada completa',
    icon: '📅',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'comp_team_player',
    name: 'Team Player',
    description: 'Participou de campeonato em equipe',
    icon: '👥',
    category: 'championship',
    requirement: { type: 'competition', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'comp_organizer',
    name: 'Organizador',
    description: 'Ajudou a organizar um evento',
    icon: '📋',
    category: 'championship',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
];
