/**
 * Badges Especiais/Comunidade - 15 badges
 */

import { BadgeDefinition } from './types';

export const specialBadges: BadgeDefinition[] = [
  {
    badgeId: 'special_booster',
    name: 'Server Booster',
    description: 'Deu boost no servidor',
    icon: '💜',
    category: 'special',
    requirement: { type: 'boost', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'special_staff',
    name: 'Staff Member',
    description: 'Membro da equipe do servidor',
    icon: '🛡️',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'special_moderator',
    name: 'Moderador',
    description: 'Moderador ativo do servidor',
    icon: '⚔️',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'special_helper',
    name: 'Helper',
    description: 'Helper oficial da comunidade',
    icon: '🤝',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'special_vip',
    name: 'VIP',
    description: 'Status VIP na comunidade',
    icon: '💠',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'special_partner',
    name: 'Parceiro',
    description: 'Parceiro oficial da comunidade',
    icon: '🤝',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'special_sponsor',
    name: 'Patrocinador',
    description: 'Patrocinador ou apoiador da comunidade',
    icon: '💰',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
  {
    badgeId: 'special_contributor',
    name: 'Contribuidor',
    description: 'Contribuiu significativamente para a comunidade',
    icon: '💡',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'rare',
  },
  {
    badgeId: 'special_tutorial',
    name: 'Tutorial Maker',
    description: 'Criou 5+ tutoriais para a comunidade',
    icon: '📖',
    category: 'special',
    requirement: { type: 'manual', value: 5 },
    rarity: 'rare',
  },
  {
    badgeId: 'special_reviewer',
    name: 'Reviewer',
    description: 'Postou 10+ reviews de produtos',
    icon: '📝',
    category: 'special',
    requirement: { type: 'manual', value: 10 },
    rarity: 'rare',
  },
  {
    badgeId: 'special_bug_hunter',
    name: 'Bug Hunter',
    description: 'Reportou bugs validos no bot ou site',
    icon: '🐛',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'uncommon',
  },
  {
    badgeId: 'special_event_host',
    name: 'Event Host',
    description: 'Hospedou evento na comunidade',
    icon: '🎉',
    category: 'special',
    requirement: { type: 'event', value: 1 },
    rarity: 'epic',
  },
  {
    badgeId: 'special_og',
    name: 'OG Member',
    description: 'Membro original da comunidade',
    icon: '🏛️',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
    limited: true,
  },
  {
    badgeId: 'special_comeback',
    name: 'Comeback',
    description: 'Retornou a comunidade apos ausencia',
    icon: '🔄',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'common',
  },
  {
    badgeId: 'special_ambassador',
    name: 'Embaixador',
    description: 'Embaixador oficial da comunidade',
    icon: '🌍',
    category: 'special',
    requirement: { type: 'manual', value: 1 },
    rarity: 'legendary',
  },
];
